title: "dire"
description: ""
about: ""
location: "right here"
email:
baseurl: ""
url: ""
twitter_username: 
# github_username:  shonin

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
projects_btn: "Projects"
posts_btn: "Posts"
imprint_btn: "About"
name_badge: "a post by"
# rss_badge: "Subscribe feed!"

# build settings
markdown: kramdown

# exclude files
exclude:
  - LICENSE
  - README.md
